import { StudentProfile } from '@/types';

export const DEFAULT_STARTER_PROFILE: StudentProfile = {
  isDemoUser: false,
  personalInfo: {
    name: 'Student Candidate',
    email: 'student@campus.edu',
    degree: 'B.Tech',
    branch: 'AI & Data Science',
    graduationYear: '2025',
    semester: '7th Semester',
    college: 'Campus Engineering College',
  },
  interests: ['Machine Learning', 'Deep Learning', 'Computer Vision', 'Data Engineering', 'Full Stack ML'],
  targetRole: 'Machine Learning Engineer',
  secondaryRoles: ['Data Scientist', 'Data Analyst', 'Backend Developer'],
  targetCompanies: ['Google', 'Microsoft', 'NVIDIA', 'Fractal Analytics', 'Swiggy', 'PhonePe'],
  availableDailyMinutes: 90,
  careerGoals: 'Crack an off-campus/on-campus ML Engineer or Data Scientist fresher role with a Tier-1 tech firm (12-20 LPA).',
  rawResumeText: `STUDENT CANDIDATE
Email: student@campus.edu | GitHub: github.com/student-dev | LinkedIn: linkedin.com/in/student-candidate

EDUCATION
B.Tech in Artificial Intelligence & Data Science | CGPA: 8.78/10 | Expected June 2025

TECHNICAL SKILLS
Languages: Python, SQL (Postgres), C++, JavaScript
Libraries/Frameworks: PyTorch, TensorFlow, Scikit-Learn, Pandas, NumPy, FastAPI
Databases & Tools: PostgreSQL, Git, Linux, Docker (Basics)

PROJECTS
1. MediScan AI - Medical Pneumonia Detection from X-Rays
- Built a CNN architecture using PyTorch & ResNet-50 with 94.2% test accuracy.
- Deployed inference API using FastAPI and lightweight React UI.
- Integrated Grad-CAM for explainable visual saliency heatmaps.

2. Smart Customer Churn Predictor
- Analyzed 50k customer records with XGBoost, achieving ROC-AUC of 0.89.
- Formulated business recommendations that projected a 14% retention uplift.

ACHIEVEMENTS & CERTIFICATIONS
- Top 5% in Kaggle Community Hackathon 2024
- Solved 180+ problems on LeetCode (Arrays, Trees, Graphs)
`,

  readiness: {
    overall: 61,
    skills: 72,
    assessment: 52,
    interview: 54,
    gd: 48,
    communication: 61,
    resume: 81,
    roleAlignment: 82,
  },

  skills: [
    {
      id: 'skill-python',
      name: 'Python for AI/Data',
      category: 'Technical',
      level: 'Strong',
      score: 84,
      marketDemand: 'Very High',
      lastAssessed: '2 days ago',
      subskills: [
        { id: 'py-1', name: 'OOP & Decorators', status: 'mastered' },
        { id: 'py-2', name: 'Vectorization (NumPy/Pandas)', status: 'mastered' },
        { id: 'py-3', name: 'Multiprocessing & Generators', status: 'practicing' },
      ],
    },
    {
      id: 'skill-ml',
      name: 'Machine Learning Algorithms',
      category: 'Technical',
      level: 'Strong',
      score: 79,
      marketDemand: 'Very High',
      lastAssessed: '4 days ago',
      subskills: [
        { id: 'ml-1', name: 'Supervised Learning & Metrics', status: 'mastered' },
        { id: 'ml-2', name: 'Feature Engineering', status: 'mastered' },
        { id: 'ml-3', name: 'Overfitting & Regularization', status: 'mastered' },
        { id: 'ml-4', name: 'Model Deployment (FastAPI)', status: 'practicing' },
      ],
    },
    {
      id: 'skill-sql',
      name: 'SQL & Relational Databases',
      category: 'Database',
      level: 'Needs Practice',
      score: 43,
      marketDemand: 'Very High',
      lastAssessed: 'Yesterday',
      subskills: [
        { id: 'sql-1', name: 'SELECT, WHERE, ORDER BY', status: 'mastered' },
        { id: 'sql-2', name: 'INNER, LEFT, FULL OUTER JOIN', status: 'weak' },
        { id: 'sql-3', name: 'Subqueries & CTEs', status: 'weak' },
        { id: 'sql-4', name: 'Window Functions (RANK, PARTITION BY)', status: 'missing' },
      ],
    },
    {
      id: 'skill-dsa',
      name: 'Data Structures & Algorithms',
      category: 'Core CS',
      level: 'Needs Practice',
      score: 46,
      marketDemand: 'Very High',
      lastAssessed: '5 days ago',
      subskills: [
        { id: 'dsa-1', name: 'Arrays & Two Pointers', status: 'mastered' },
        { id: 'dsa-2', name: 'Binary Trees & Traversals', status: 'practicing' },
        { id: 'dsa-3', name: 'Dynamic Programming', status: 'weak' },
        { id: 'dsa-4', name: 'Graph Algorithms', status: 'missing' },
      ],
    },
    {
      id: 'skill-docker',
      name: 'Docker & Containerization',
      category: 'Framework',
      level: 'Missing',
      score: 28,
      marketDemand: 'High',
      lastAssessed: 'Not assessed',
      subskills: [
        { id: 'doc-1', name: 'Dockerfiles & Image Layering', status: 'weak' },
        { id: 'doc-2', name: 'Docker Compose for ML Services', status: 'missing' },
      ],
    },
    {
      id: 'skill-comm',
      name: 'Technical Communication & Clarity',
      category: 'Soft Skills',
      level: 'Good',
      score: 61,
      marketDemand: 'Very High',
      lastAssessed: '3 days ago',
      subskills: [
        { id: 'com-1', name: 'Structured Answer Delivery (STAR)', status: 'practicing' },
        { id: 'com-2', name: 'Conciseness & Filler Words Control', status: 'weak' },
        { id: 'com-3', name: 'Explaining Architecture Tradeoffs', status: 'practicing' },
      ],
    },
  ],

  nextBestAction: {
    id: 'nba-sql-joins',
    title: 'Master SQL JOINs & Multi-Table Aggregations',
    category: 'learning',
    description: 'Close your single biggest gap before on-campus technical screen rounds.',
    why: 'Your last 2 assessments showed 43% accuracy on multi-table JOINs and GROUP BY queries, a mandatory test topic for Machine Learning & Data roles.',
    timeEstimate: '15 minutes',
    priority: 'High',
    actionUrl: '/learning/module-sql-joins',
    actionText: 'Start 15-Min Focused Practice',
  },

  learningModules: [
    {
      id: 'module-sql-joins',
      title: 'SQL JOIN Deep-Dive: From Fundamentals to Complex Joins',
      topic: 'SQL & Relational Databases',
      category: 'Database',
      description: 'Master INNER, LEFT, RIGHT, FULL OUTER, and CROSS joins with real interview query patterns.',
      whyNeeded: 'Critical bottleneck identified in your last SQL assessment (scored 43%).',
      difficulty: 'Beginner',
      estimatedTime: '15 mins',
      prerequisites: ['Basic SELECT queries', 'WHERE clauses'],
      scoreBoostEstimate: 14,
      relatedSkill: 'skill-sql',
      completed: false,
      resources: [
        {
          title: 'PostgreSQL Official: Tutorial on Joins',
          type: 'documentation',
          url: 'https://www.postgresql.org/docs/current/tutorial-join.html',
          provider: 'Official PostgreSQL Docs',
          duration: '5 mins read',
        },
        {
          title: 'SQL Joins Explained Visually in 10 Minutes',
          type: 'video',
          url: 'https://www.youtube.com/watch?v=9yeOJ0ZMUYw',
          provider: 'YouTube (freeCodeCamp)',
          duration: '10 mins video',
        },
        {
          title: 'Interactive SQL JOIN Practice Lab',
          type: 'interactive',
          url: 'https://sqlbolt.com/lesson/select_queries_with_joins',
          provider: 'SQLBolt Free Interactive Sandbox',
          duration: '10 mins hands-on',
        },
      ],
      keyTakeaways: [
        'INNER JOIN returns records that have matching values in both tables.',
        'LEFT JOIN preserves all records from the left table and populates NULLs where the right table has no match.',
        'Self JOIN is essential when querying hierarchical employee-manager tables.',
        'Watch out for cartesian product bugs when forgetting ON join predicates.',
      ],
    },
    {
      id: 'module-dsa-trees',
      title: 'Binary Trees & BFS/DFS for Coding Rounds',
      topic: 'Data Structures & Algorithms',
      category: 'Core CS',
      description: 'Learn standard traversal patterns, recursion templates, and level-order traversal for tech interviews.',
      whyNeeded: 'Required for technical rounds at Microsoft, Swiggy, and Fractal.',
      difficulty: 'Intermediate',
      estimatedTime: '25 mins',
      prerequisites: ['Recursion basics', 'Pointers / References'],
      scoreBoostEstimate: 10,
      relatedSkill: 'skill-dsa',
      completed: false,
      resources: [
        {
          title: 'Tree Traversals (Inorder, Preorder, Postorder)',
          type: 'documentation',
          url: 'https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/',
          provider: 'GeeksforGeeks',
          duration: '8 mins',
        },
        {
          title: 'NeetCode: Binary Tree Inorder Traversal',
          type: 'video',
          url: 'https://www.youtube.com/watch?v=g_S5WuasWUE',
          provider: 'YouTube (NeetCode)',
          duration: '12 mins',
        },
      ],
      keyTakeaways: [
        'Recursive vs Iterative traversal using explicit stack.',
        'BFS uses a Queue; DFS uses a Stack/Recursion.',
      ],
    },
    {
      id: 'module-docker-basics',
      title: 'Docker Containerization for Machine Learning Engineers',
      topic: 'Cloud & DevOps',
      category: 'Framework',
      description: 'Package your PyTorch & FastAPI microservices into reproducible, deployable Docker containers.',
      whyNeeded: '82% of fresher ML postings on LinkedIn require Docker fundamentals.',
      difficulty: 'Beginner',
      estimatedTime: '20 mins',
      prerequisites: ['Basic Linux terminal commands', 'Python virtual environments'],
      scoreBoostEstimate: 12,
      relatedSkill: 'skill-docker',
      completed: false,
      resources: [
        {
          title: 'Docker for Beginners - Full Guide',
          type: 'documentation',
          url: 'https://docs.docker.com/get-started/',
          provider: 'Docker Official Documentation',
          duration: '10 mins',
        },
        {
          title: 'Deploy ML Models with Docker & FastAPI',
          type: 'video',
          url: 'https://www.youtube.com/watch?v=h5wLuVDr0oc',
          provider: 'YouTube',
          duration: '15 mins',
        },
      ],
      keyTakeaways: [
        'Writing clean multi-stage Dockerfiles.',
        'Handling CUDA vs CPU runtime environments.',
      ],
    },
  ],

  assessments: [
    {
      id: 'assessment-sql-diagnostic',
      title: 'SQL Relational Diagnostic Test',
      category: 'SQL & Database',
      roleTarget: 'Machine Learning Engineer',
      description: 'Evaluates your mastery of JOIN conditions, GROUP BY aggregations, and subqueries with instant gap feedback.',
      estimatedMinutes: 10,
      questionsCount: 5,
      difficulty: 'Adaptive',
      attemptsCount: 1,
      highestScore: 43,
      questions: [
        {
          id: 'q-sql-1',
          topic: 'SQL JOINs',
          difficulty: 'Easy',
          question: 'Consider two tables: `Users` (id, name) and `Orders` (id, user_id, amount). Which query returns ALL users, including those who have never placed an order?',
          options: [
            'SELECT Users.name, Orders.amount FROM Users INNER JOIN Orders ON Users.id = Orders.user_id;',
            'SELECT Users.name, Orders.amount FROM Users LEFT JOIN Orders ON Users.id = Orders.user_id;',
            'SELECT Users.name, Orders.amount FROM Users RIGHT JOIN Orders ON Users.id = Orders.user_id;',
            'SELECT Users.name, Orders.amount FROM Users CROSS JOIN Orders;',
          ],
          correctAnswer: 1,
          explanation: 'LEFT JOIN returns all records from the left table (`Users`), and the matched records from the right table (`Orders`). If there is no match, the right side results in NULL.',
        },
        {
          id: 'q-sql-2',
          topic: 'SQL Aggregations',
          difficulty: 'Medium',
          question: 'What is the key difference between the WHERE clause and the HAVING clause in SQL?',
          options: [
            'WHERE filters rows after aggregation; HAVING filters rows before aggregation.',
            'HAVING filters groups created by GROUP BY after aggregation; WHERE filters individual rows before aggregation.',
            'There is no difference; they are interchangeable in standard SQL.',
            'HAVING can only be used with primary key columns.',
          ],
          correctAnswer: 1,
          explanation: 'The WHERE clause filters individual rows before any grouping or aggregation takes place. The HAVING clause filters grouped results created by aggregate functions (e.g., COUNT, SUM).',
        },
        {
          id: 'q-sql-3',
          topic: 'SQL Self-Join',
          difficulty: 'Medium',
          question: 'In an `Employees` table with columns (emp_id, emp_name, manager_id), how do you find employees whose salary is higher than their manager’s salary?',
          options: [
            'Use a self-join: `FROM Employees e JOIN Employees m ON e.manager_id = m.emp_id WHERE e.salary > m.salary`',
            'Use a CROSS JOIN with `GROUP BY e.salary`',
            'You cannot compare rows in the same table without creating two physical tables',
            'Use `UNION ALL` with `HAVING e.salary > m.salary`',
          ],
          correctAnswer: 0,
          explanation: 'A self-join aliases the same table twice (as employee `e` and manager `m`), matching `e.manager_id = m.emp_id` and filtering where `e.salary > m.salary`.',
        },
        {
          id: 'q-sql-4',
          topic: 'SQL Window Functions',
          difficulty: 'Hard',
          question: 'Which window function should you use to find the second highest salary in each department while properly handling identical salaries with no gaps in ranking?',
          options: [
            'RANK() OVER (PARTITION BY department_id ORDER BY salary DESC)',
            'DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC)',
            'ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC)',
            'NTILE(2) OVER (ORDER BY salary)',
          ],
          correctAnswer: 1,
          explanation: '`DENSE_RANK()` assigns consecutive rank values without leaving gaps when multiple employees share the same top salary. `RANK()` would skip ranks on ties.',
        },
        {
          id: 'q-sql-5',
          topic: 'SQL NULL Handling',
          difficulty: 'Medium',
          question: 'What does the query `SELECT COUNT(*), COUNT(commission) FROM Sales;` return if 3 out of 10 rows have a NULL commission?',
          options: [
            '10, 10',
            '10, 7',
            '7, 7',
            'Throws a runtime SQL NULL exception',
          ],
          correctAnswer: 1,
          explanation: '`COUNT(*)` counts all rows regardless of NULL values (10), while `COUNT(column)` only counts non-NULL rows in that specific column (10 - 3 = 7).',
        },
      ],
    },
    {
      id: 'assessment-ml-eval',
      title: 'Machine Learning Concepts & Metrics',
      category: 'Machine Learning',
      roleTarget: 'Machine Learning Engineer',
      description: 'Test your understanding of classification metrics, precision-recall tradeoffs, regularization, and overfitting.',
      estimatedMinutes: 12,
      questionsCount: 4,
      difficulty: 'Standard',
      attemptsCount: 0,
      highestScore: undefined,
      questions: [
        {
          id: 'q-ml-1',
          topic: 'Evaluation Metrics',
          difficulty: 'Medium',
          question: 'In a medical cancer detection model where failing to detect an actual positive case has fatal consequences, which metric should be prioritized most?',
          options: [
            'Specificity',
            'Recall (Sensitivity)',
            'Precision',
            'Accuracy',
          ],
          correctAnswer: 1,
          explanation: 'Recall measures True Positives / (True Positives + False Negatives). Minimizing False Negatives (missed cancer cases) requires maximizing Recall.',
        },
        {
          id: 'q-ml-2',
          topic: 'Regularization',
          difficulty: 'Medium',
          question: 'Which regularization technique tends to push non-informative feature weights strictly to zero, performing automatic feature selection?',
          options: [
            'L2 Regularization (Ridge)',
            'L1 Regularization (Lasso)',
            'Dropout with p=0.1',
            'Batch Normalization',
          ],
          correctAnswer: 1,
          explanation: 'L1 (Lasso) penalty adds the absolute sum of weights, which produces sparse weight vectors with exact zeros, acting as embedded feature selection.',
        },
        {
          id: 'q-ml-3',
          topic: 'Bias-Variance Tradeoff',
          difficulty: 'Hard',
          question: 'If a deep neural network achieves 99.4% training accuracy but only 68.1% validation accuracy, what is the primary diagnosis and immediate remedy?',
          options: [
            'High Bias (Underfitting); increase model parameters and remove regularization.',
            'High Variance (Overfitting); add dropout, data augmentation, or early stopping.',
            'Data drift; retrain with fewer iterations.',
            'Learning rate is too small; multiply learning rate by 10x.',
          ],
          correctAnswer: 1,
          explanation: 'A huge gap between near-perfect training accuracy and poor validation accuracy is the textbook signature of High Variance (Overfitting). Regularization and augmentation help bridge this gap.',
        },
        {
          id: 'q-ml-4',
          topic: 'Gradient Descent',
          difficulty: 'Medium',
          question: 'What is the main advantage of the Adam optimizer over standard Stochastic Gradient Descent (SGD) with momentum?',
          options: [
            'Adam guarantees convergence to the global optimum on all non-convex loss surfaces.',
            'Adam adapts individual learning rates for each parameter based on first and second moments of the gradients.',
            'Adam does not require backpropagation to compute derivatives.',
            'Adam uses zero memory buffer.',
          ],
          correctAnswer: 1,
          explanation: 'Adam (Adaptive Moment Estimation) computes individual adaptive learning rates for different parameters from estimates of first (mean) and second (uncentered variance) moments of the gradients.',
        },
      ],
    },
  ],

  assessmentHistory: [
    {
      id: 'attempt-sql-prev',
      assessmentId: 'assessment-sql-diagnostic',
      title: 'SQL Relational Diagnostic Test',
      category: 'SQL & Database',
      date: 'Yesterday at 4:30 PM',
      score: 43,
      totalQuestions: 5,
      correctAnswersCount: 2,
      weakAreas: ['SQL JOIN conditions', 'Self-Join syntax', 'Window functions'],
      strongAreas: ['Basic SELECT', 'Aggregations WHERE vs HAVING'],
      recommendedLearningId: 'module-sql-joins',
      answers: [
        { questionId: 'q-sql-1', selectedOption: 0, isCorrect: false },
        { questionId: 'q-sql-2', selectedOption: 1, isCorrect: true },
        { questionId: 'q-sql-3', selectedOption: 2, isCorrect: false },
        { questionId: 'q-sql-4', selectedOption: 0, isCorrect: false },
        { questionId: 'q-sql-5', selectedOption: 1, isCorrect: true },
      ],
    },
  ],

  gdSessions: [
    {
      id: 'gd-session-1',
      topic: 'Will Generative AI Eliminate Entry-Level Engineering Roles or Accelerate Them?',
      category: 'AI & Tech',
      context: 'With LLMs writing 40%+ of boilerplate code, tech firms are rethinking campus hiring expectations. Does the industry still need freshers, or do freshers need to evolve into AI-augmented problem solvers?',
      rules: [
        'Maintain professional decorum; no personal attacks.',
        'Support arguments with data, industry examples, or practical project observations.',
        'Avoid dominating speech; ensure inclusive turn-taking.',
        'Keep opening statements strictly under 45 seconds.',
      ],
      date: 'Today, Live Peer Room',
      time: 'Immediate / Scheduled (7:00 PM)',
      durationMinutes: 30,
      maxParticipants: 8,
      currentParticipants: 5,
      isBookedByMe: false,
      meetLink: 'https://meet.jit.si/Placement360_GD_AI_Future_Room',
      isRealMeeting: true,
      meetingType: 'jitsi-live',
      status: 'upcoming',
    },
    {
      id: 'gd-session-2',
      topic: 'Moonlighting and Remote Work in IT: Ethical Right vs Breach of Contract?',
      category: 'Ethics & Society',
      context: 'Post-pandemic hybrid policies have reignited debates over dual employment, confidentiality, and productivity measurement in modern software companies.',
      rules: [
        'Differentiate between legal compliance and ethical responsibility.',
        'Address employer IP safety versus employee personal autonomy.',
      ],
      date: 'Tomorrow, Sunday',
      time: '5:30 PM IST',
      durationMinutes: 25,
      maxParticipants: 8,
      currentParticipants: 7,
      isBookedByMe: false,
      meetLink: 'https://meet.jit.si/Placement360_GD_Remote_Work_Ethics',
      isRealMeeting: true,
      meetingType: 'jitsi-live',
      status: 'upcoming',
    },
    {
      id: 'gd-session-3',
      topic: 'Centralized Cloud Infrastructure vs Edge Computing for Autonomous Vehicles',
      category: 'Business & Economy',
      context: 'Evaluating latency, 5G reliability, computational power, and cost efficiency in real-time mission-critical AI systems.',
      rules: [
        'Focus on engineering constraints (latency, packet loss, bandwidth).',
      ],
      date: 'Next Tuesday',
      time: '8:00 PM IST',
      durationMinutes: 30,
      maxParticipants: 8,
      currentParticipants: 3,
      isBookedByMe: false,
      meetLink: 'https://meet.jit.si/Placement360_GD_Edge_Vs_Cloud',
      isRealMeeting: true,
      meetingType: 'jitsi-live',
      status: 'upcoming',
    },
  ],

  gdHistory: [
    {
      sessionId: 'gd-session-prev',
      sessionTopic: 'Ethics of Autonomous AI Agents in Defense and Medicine',
      date: '3 days ago',
      overallScore: 48,
      participation: 50,
      relevance: 72,
      clarity: 55,
      structure: 45,
      strengths: [
        'Brought up relevant medical diagnosis liability examples.',
        'Polite listening behavior while others spoke.',
      ],
      recommendedImprovements: [
        'Entered the discussion late (after 7 minutes of silence); aim to initiate or enter by minute 3.',
        'Did not structure points using the PREP framework (Point, Reason, Example, Point).',
        'Did not summarize or offer synthesis towards the end of the session.',
      ],
    },
  ],

  interviewAttempts: [
    {
      id: 'interview-prev-1',
      mode: 'project-defense',
      targetRole: 'Machine Learning Engineer',
      date: '4 days ago',
      overallScore: 54,
      questionsCount: 3,
      dialogue: [
        {
          question: 'Explain your MediScan AI project. What exact problem did it solve, and why did you choose ResNet-50?',
          studentAnswer: 'Basically MediScan is an AI project I built using PyTorch to detect pneumonia from chest X-rays. I chose ResNet-50 because it is popular and has skip connections so gradients do not vanish. It had 94% accuracy.',
          evaluation: {
            technicalAccuracy: 78,
            relevance: 75,
            structure: 50,
            clarity: 62,
            overallScore: 66,
            feedbackSummary: 'Good technical base, but answer lacks quantifiable business context, dataset details, and metric specificity (was it accuracy or recall?).',
            fillerWordsDetected: ['Basically', 'you know'],
            improvementPoints: [
              'Start with a 1-sentence executive hook: problem magnitude, dataset size, and patient impact.',
              'Explain why accuracy alone is deceptive on imbalanced medical datasets (mention Sensitivity/Recall).',
            ],
            followUpQuestion: 'Given that pneumonia false negatives are catastrophic, what was your model’s False Negative rate and how did you balance precision vs recall?',
          },
        },
      ],
    },
  ],

  resumeAnalysis: {
    targetRole: 'Machine Learning Engineer',
    overallScore: 81,
    keywordMatch: 82,
    skillMatch: 79,
    projectMatch: 88,
    roleAlignment: 82,
    extractedName: 'Student Candidate',
    extractedEmail: 'student@campus.edu',
    extractedSkills: ['Python', 'PyTorch', 'TensorFlow', 'Scikit-Learn', 'FastAPI', 'PostgreSQL', 'Git', 'Linux'],
    matchedKeywords: ['CNN', 'ResNet-50', 'PyTorch', 'Model Deployment', 'FastAPI', 'XGBoost', 'ROC-AUC', 'SQL'],
    missingKeywords: ['Docker containerization', 'CI/CD pipeline for ML (MLOps)', 'Unit Testing / pytest', 'AWS / Cloud Deployments', 'Kafka / Streaming'],
    strengths: [
      'Strong quantifiable metrics in projects (94.2% test accuracy, 14% retention uplift).',
      'Solid combination of core ML frameworks (PyTorch, Scikit-Learn) with deployment tool (FastAPI).',
      'Clean typography and single-page ATS-parseable structure.',
    ],
    criticalGaps: [
      'Missing Docker / containerized deployment mentions in projects.',
      'Database section mentions PostgreSQL, but no evidence of complex schema design or optimization.',
      'No explicit mention of MLOps or automated model evaluation pipelines.',
    ],
    actionableRecommendations: [
      'Add a bullet point under MediScan AI explaining Docker containerization and latency benchmarks.',
      'Highlight SQL schema design or query optimization in customer churn project.',
      'Include links to live GitHub repositories with clean README files and demo GIFs.',
    ],
    freeBuilderUrl: 'https://rxresu.me/',
  },

  jobMatches: [
    {
      id: 'job-1',
      title: 'Software Engineering Intern (Summer 2025/2026)',
      company: 'Google',
      location: 'Bengaluru / Hyderabad',
      type: 'Internship',
      source: 'Google Careers',
      matchScore: 91,
      strongMatches: ['Data Structures', 'Python', 'Algorithms', 'FastAPI'],
      missingSkills: ['Distributed Systems', 'System Design'],
      experienceRequired: 'Pre-final / Final Year B.Tech',
      salaryOrStipend: '₹1,10,000 / month stipend',
      postedDate: 'Just now',
      whyMatchesExplanation: 'Exceptional alignment on algorithmic problem solving, Kaggle hackathon performance, and clean Python backend architecture.',
      originalJobUrl: 'https://www.google.com/about/careers/applications/jobs/results/?q=software%20engineer%20intern',
      marketUrgency: 'High',
    },
    {
      id: 'job-2',
      title: 'Software Development Engineer (SDE) - Campus 2025',
      company: 'Amazon India',
      location: 'Bengaluru / Hyderabad / Chennai',
      type: 'Full-time',
      source: 'Amazon Jobs',
      matchScore: 86,
      strongMatches: ['Python', 'DSA', 'OOP Principles', 'Problem Solving'],
      missingSkills: ['Java/C++ Production Code', 'AWS Cloud'],
      experienceRequired: '0 - 1 Years / 2025 Grad',
      salaryOrStipend: '₹16.0 - ₹28.0 LPA',
      postedDate: '1 day ago',
      whyMatchesExplanation: 'Strong baseline on LeetCode data structures and analytical coding. Closing your tree traversal gaps positions you for Amazon SDE rounds.',
      originalJobUrl: 'https://www.amazon.jobs/en/search?base_query=software+development+engineer+intern&loc_query=India',
      marketUrgency: 'High',
    },
    {
      id: 'job-3',
      title: 'Machine Learning Research Intern',
      company: 'Microsoft India',
      location: 'Hyderabad / Bengaluru',
      type: 'Internship',
      source: 'LinkedIn',
      matchScore: 84,
      strongMatches: ['Deep Learning', 'PyTorch', 'Data Structures', 'CGPA 8.5+'],
      missingSkills: ['Distributed Training', 'Research Paper Publications'],
      experienceRequired: 'Intern (6 Months)',
      salaryOrStipend: '₹1,25,000 / month stipend',
      postedDate: '2 days ago',
      whyMatchesExplanation: 'Your Kaggle standing and high academic CGPA (8.78) qualify for Microsoft India campus research pool.',
      originalJobUrl: 'https://www.linkedin.com/jobs/search/?keywords=Microsoft+Machine+Learning+Intern&location=India',
      marketUrgency: 'High',
    },
    {
      id: 'job-4',
      title: 'Machine Learning Engineer - Fresher (Campus 2025)',
      company: 'Fractal Analytics',
      location: 'Bengaluru / Hyderabad (Hybrid)',
      type: 'Full-time',
      source: 'LinkedIn',
      matchScore: 88,
      strongMatches: ['Python', 'PyTorch', 'Scikit-Learn', 'FastAPI', 'Problem Solving'],
      missingSkills: ['Docker', 'SQL Advanced Queries'],
      experienceRequired: '0 - 1 Years / 2025 Batch',
      salaryOrStipend: '₹9.5 - ₹13.0 LPA',
      postedDate: '2 days ago',
      whyMatchesExplanation: 'Your PyTorch and ResNet project alignment matches 88% of their Vision/NLP fresher requisition.',
      originalJobUrl: 'https://www.linkedin.com/jobs/search/?keywords=Fractal+Machine+Learning+Fresher&location=India',
      marketUrgency: 'High',
    },
    {
      id: 'job-5',
      title: 'Machine Learning & AI Internships',
      company: 'Verified Tech Startups',
      location: 'Remote / Work From Home',
      type: 'Internship',
      source: 'Internshala',
      matchScore: 92,
      strongMatches: ['Python', 'Computer Vision', 'PyTorch', 'FastAPI'],
      missingSkills: ['Docker Deployment'],
      experienceRequired: 'Fresher / College Students',
      salaryOrStipend: '₹25,000 - ₹50,000 / month',
      postedDate: 'Live Feed',
      whyMatchesExplanation: 'Immediate synergy with startup project requirements looking for hands-on PyTorch model building.',
      originalJobUrl: 'https://internshala.com/internships/machine-learning-internship/',
      marketUrgency: 'Trending',
    },
    {
      id: 'job-6',
      title: 'Web & Full Stack Development Internships',
      company: 'Product Companies & Startups',
      location: 'Delhi NCR / Bengaluru / Remote',
      type: 'Internship',
      source: 'Internshala',
      matchScore: 79,
      strongMatches: ['JavaScript', 'React', 'FastAPI REST', 'Git'],
      missingSkills: ['TypeScript Advanced', 'Database Indexing'],
      experienceRequired: 'College Students (All Semesters)',
      salaryOrStipend: '₹20,000 - ₹45,000 / month',
      postedDate: 'Live Feed',
      whyMatchesExplanation: 'High demand for developers who can integrate AI models with modern responsive web interfaces.',
      originalJobUrl: 'https://internshala.com/internships/web-development-internship/',
      marketUrgency: 'Normal',
    },
    {
      id: 'job-7',
      title: 'Data Science & Analytics Internships',
      company: 'Analytics Consultancies',
      location: 'Mumbai / Pune / Remote',
      type: 'Internship',
      source: 'Internshala',
      matchScore: 85,
      strongMatches: ['Python', 'Pandas', 'XGBoost', 'Exploratory Data Analysis'],
      missingSkills: ['SQL JOINs', 'PowerBI'],
      experienceRequired: 'Final Year / Freshers',
      salaryOrStipend: '₹30,000 - ₹60,000 / month',
      postedDate: 'Live Feed',
      whyMatchesExplanation: 'Direct match with customer churn analytics and statistical modeling credentials.',
      originalJobUrl: 'https://internshala.com/internships/data-science-internship/',
      marketUrgency: 'Trending',
    },
    {
      id: 'job-8',
      title: 'Graduate Engineer Trainee & Tech Challenges',
      company: 'Top Tech Recruiters',
      location: 'Pan-India',
      type: 'Fresher Role',
      source: 'Unstop',
      matchScore: 87,
      strongMatches: ['Aptitude', 'Problem Solving', 'Data Structures', 'CS Fundamentals'],
      missingSkills: ['Operating Systems In-Depth'],
      experienceRequired: '2024 / 2025 / 2026 Batch',
      salaryOrStipend: '₹7.0 - ₹15.0 LPA',
      postedDate: 'Live Competitions',
      whyMatchesExplanation: 'Direct hiring hackathons and national campus recruitment drives from top enterprises.',
      originalJobUrl: 'https://unstop.com/job-portal',
      marketUrgency: 'High',
    },
    {
      id: 'job-9',
      title: 'Associate Data Scientist',
      company: 'Swiggy',
      location: 'Bengaluru (In-Office)',
      type: 'Full-time',
      source: 'Naukri',
      matchScore: 81,
      strongMatches: ['Python', 'XGBoost', 'Feature Engineering', 'Statistical Analysis'],
      missingSkills: ['Complex SQL Subqueries', 'A/B Testing Methodology'],
      experienceRequired: 'Fresher / Final Year B.Tech',
      salaryOrStipend: '₹14.0 - ₹18.0 LPA',
      postedDate: '3 days ago',
      whyMatchesExplanation: 'Your customer churn project using XGBoost demonstrates direct synergy with Swiggy retention analytics requirements.',
      originalJobUrl: 'https://www.naukri.com/data-scientist-fresher-jobs',
      marketUrgency: 'Trending',
    },
    {
      id: 'job-10',
      title: 'Python / ML Fresher Openings',
      company: 'Verified Tech Firms',
      location: 'India (Multiple Cities)',
      type: 'Full-time',
      source: 'Indeed',
      matchScore: 83,
      strongMatches: ['Python', 'Pandas', 'REST APIs', 'FastAPI'],
      missingSkills: ['SQL Optimization'],
      experienceRequired: '0 - 1 Years',
      salaryOrStipend: '₹6.5 - ₹11.0 LPA',
      postedDate: 'Updated Today',
      whyMatchesExplanation: 'Aggregated verified openings matching entry-level Python script and model deployment requirements.',
      originalJobUrl: 'https://in.indeed.com/jobs?q=Python+Machine+Learning+Fresher&l=India',
      marketUrgency: 'Normal',
    },
    {
      id: 'job-11',
      title: 'AI / Full Stack Startup Roles',
      company: 'Y Combinator & High-Growth Startups',
      location: 'Remote / Hybrid',
      type: 'Full-time',
      source: 'Wellfound',
      matchScore: 85,
      strongMatches: ['FastAPI', 'PyTorch', 'Independent Shipping', 'Full Stack ML'],
      missingSkills: ['Cloud Infrastructure'],
      experienceRequired: 'Fresher to 1 Year',
      salaryOrStipend: '₹12.0 - ₹22.0 LPA + Equity',
      postedDate: 'Live Feed',
      whyMatchesExplanation: 'Early stage startups looking for self-starters who can ship machine learning prototypes directly to production.',
      originalJobUrl: 'https://wellfound.com/jobs',
      marketUrgency: 'Trending',
    },
    {
      id: 'job-12',
      title: 'TCS National Qualifier Test (NQT) Hiring',
      company: 'Tata Consultancy Services',
      location: 'Pan-India',
      type: 'Fresher Role',
      source: 'Company Career Board',
      matchScore: 80,
      strongMatches: ['Cognitive Skills', 'Programming Logic', 'CS Core'],
      missingSkills: ['Business Communication'],
      experienceRequired: '2024 / 2025 Graduating Batch',
      salaryOrStipend: '₹3.6 - ₹9.0 LPA (Ninja / Digital / Prime)',
      postedDate: 'Active Cohort',
      whyMatchesExplanation: 'Direct entry into TCS Digital / Prime campus hiring streams based on technical performance.',
      originalJobUrl: 'https://www.tcsion.com/hub/national-qualifier-test/',
      marketUrgency: 'High',
    },
  ],

  achievements: [
    {
      id: 'ach-1',
      title: 'Placement Twin Initialized',
      description: 'Completed multi-step onboarding and established baseline preparation readiness.',
      date: 'Sep 22, 2026',
      icon: 'sparkles',
    },
    {
      id: 'ach-2',
      title: 'Resume ATS Benchmark',
      description: 'Achieved an initial ATS-style compatibility score of 81% for ML Engineer role.',
      date: 'Sep 23, 2026',
      icon: 'file-check',
    },
    {
      id: 'ach-3',
      title: 'First Diagnostic Attempt',
      description: 'Identified SQL JOINs as the critical preparation bottleneck to resolve.',
      date: 'Sep 24, 2026',
      icon: 'target',
    },
  ],

  weeklyProgressHistory: [
    { week: 'Week 1', readiness: 48, sqlScore: 35, gdScore: 40, interviewScore: 42 },
    { week: 'Week 2', readiness: 54, sqlScore: 38, gdScore: 44, interviewScore: 49 },
    { week: 'Week 3', readiness: 61, sqlScore: 43, gdScore: 48, interviewScore: 54 },
  ],
};

export const INITIAL_DEMO_STUDENT = DEFAULT_STARTER_PROFILE;

